# This workflow will install a prebuilt Ruby version, install dependencies, and run tests and linters.
name: "Ruby on Rails CI"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      RAILS_ENV: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      # Install Ruby and gems
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Set up the database schema
      - name: Set up database schema
        run: bin/rails db:schema:load

      # Run tests
      - name: Run tests
        run: bin/rake test

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Install Ruby and gems
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      # Generate binstubs for linters and security tools
      - name: Generate binstubs
        run: bundle binstubs bundler-audit brakeman rubocop

      # Security audit dependencies
      - name: Security audit dependencies
        run: bin/bundler-audit --update

      # Security audit application code
      - name: Security audit application code
        run: bin/brakeman -q -w2

      # Lint Ruby files
      - name: Lint Ruby files
        run: bin/rubocop --parallel
